AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  manutd-ecosystem
  SAM Template for Manchester United Automated Data Pipeline

Resources:
  # Infrastructure will be defined here in Phase 1
